import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import localFont from "next/font/local";
import Header from "./components/layout/Header";
import "./globals.css";

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-eb-garamond",
  display: "swap",
});

const helveticaNeue = localFont({
  src: '../public/fonts/HelveticaNeue-Medium.woff2',
  weight: '500',
  style: 'normal',
  variable: '--font-helvetica-neue',
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ebGaramond.variable} ${helveticaNeue.variable} font-sans antialiased background`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
