import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import localFont from "next/font/local";
import Header from "./components/layout/Header";
import "./globals.css";
import Menu from "./components/layout/Menu";

// const ebGaramond = EB_Garamond({
//   subsets: ["latin"],
//   variable: "--font-eb-garamond",
//   display: "swap",
// });

const ebGaramond = localFont({
  src: '../public/fonts/ITC-Garamond-Std-Book-Narrow.woff2',
  weight: '500',
  style: 'normal',
  variable: '--font-eb-garamond',
  display: 'swap',
  preload: true,
});

const helveticaNeue = localFont({
  src: '../public/fonts/HelveticaNeue-Medium.woff2',
  weight: '500',
  style: 'normal',
  variable: '--font-helvetica-neue',
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ebGaramond.variable} ${helveticaNeue.variable} font-primary antialiased relative`}>
        <div className="absolute w-full h-full bg-repeat mix-blend-multiply pointer-events-none bg-size-[150px_150px] bg-[url('/tale1.png')]"></div>
        <Header />
        <Menu />
        {children}
      </body>
    </html>
  );
}
